#ifndef DEFS_H
#define DEFS_H

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define PLAYER_SPEED 400
#define BULLET_SPEED 10
#define PLAYER_RELOAD (2 * BULLET_SPEED)

#define RAWS_OF_ENEMIES 5
#define COLUMNS_OF_ENEMIES 11
#define ENEMIES_SPEED 20
#define ENEMIES_GAP_X 20
#define ENEMIES_GAP_Y 10
#define TOP_OFFSET_ENEMIES 100
#define ENEMIES_TICK_DELAY 20

#endif